config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :welcome, path: '/' do
    collection do 
      get 'oauth2callback'
      get 'auth_link'
      get 'analytics'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #i have changedd

  
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def auth_link
    #this is adding comment only
    #added one more commit
    #hcnage in welcome contoller
    
    client = Signet::OAuth2::Client.new({
      client_id: '1047963797640-oohtkqo7iebvj61mhqdl9n72t0rnpcae.apps.googleusercontent.com',
      client_secret: 'Yc6idcadksN_-2KHLLiEPNUO',
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      scope: Google::Apis::AnalyticsV3::AUTH_ANALYTICS_READONLY,
      redirect_uri: url_for(:action => :oauth2callback)
    })
    # byebug
    redirect_to client.authorization_uri.to_s
  end

  def oauth2callback
    #this is auth mehtod only
    client = Signet::OAuth2::Client.new({
      client_id: '1047963797640-oohtkqo7iebvj61mhqdl9n72t0rnpcae.apps.googleusercontent.com',
      client_secret: 'Yc6idcadksN_-2KHLLiEPNUO',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      redirect_uri: url_for(:action => :oauth2callback),
      code: params[:code]

      #add one more space
    })

    @response = client.fetch_access_token!
    # byebug
    session[:access_token] = @response['access_token']

    redirect_to url_for(:action => :analytics)
  end

  def analytics
    client = Signet::OAuth2::Client.new(access_token: session[:access_token])

    service = Google::Apis::AnalyticsV3::AnalyticsService.new
    # byebug
    service.authorization = client

    @account_summaries = service.list_account_summaries
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/analytics.html.erb
token <%= session[:access_token] %>

<p>
  <%= @response.inspect %>

</p>


<ul>
  <% @account_summaries.items.each do |item| %>
    <li><%= item.name %> (<%= item.id %>)
      <ul>
        <% item.web_properties.each do |property| %>
          <li><%= property.name %> (<%= property.id %>)
            <ul>
              <% property.profiles.each do |profile| %>
                <li><%= profile.name %> (<%= profile.id %>)</li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<%= link_to "oauth link", auth_link_welcome_index_path %>